---
all:
  children:
    control_plane:
      hosts:
        k8s-control-01:
          ansible_host: 192.168.50.210
    workers:
      hosts:
        k8s-worker-01:
          ansible_host: 192.168.50.211
        k8s-worker-02:
          ansible_host: 192.168.50.212
    k8s_cluster:
      children:
        control_plane: {}
        workers: {}
  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: ~/.ssh/homelab-dev
    pod_cidr: 10.244.0.0/16
