controllers:
  main:
    containers:
      main:
        image:
          repository: homeassistant/home-assistant
          tag: latest
        env:
          TZ: "Europe/London"

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: true
    hosts:
      - host: home.nooney.dev
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

hostNetwork: true

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi
