controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/prowlarr
          tag: latest
        env:
          TZ: "America/New_York"
          PUID: "1000"
          PGID: "1000"

service:
  main:
    ports:
      http:
        port: 9696

ingress:
  main:
    enabled: true
    hosts:
      - host: prowlarr.nooney.dev
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
