image:
  repository: linuxserver/transmission
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: "America/New_York"
  PUID: "1000"
  PGID: "1000"

service:
  web:
    type: ClusterIP
    port: 9091
    annotations: {}
  torrent:
    enabled: true
    type: LoadBalancer
    tcpPort: 51413
    udpPort: 51413
    annotations: {}

ingress:
  main:
    enabled: true
    hosts:
      - host: transmission.nooney.dev
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 5Gi
    existingClaim: ""
  downloads:
    enabled: true
    type: nfs
    nfsServer: "nfs-server.example.com"
    nfsPath: "/mnt/downloads"
    storageClassName: ""
    accessMode: ReadWriteMany
    size: 100Gi
    existingClaim: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
