controllers:
  main:
    containers:
      main:
        image:
          repository: plexinc/pms-docker
          tag: latest
        env:
          TZ: "America/New_York"
          PLEX_CLAIM: ""

service:
  main:
    type: NodePort
    ports:
      http:
        port: 32400
        nodePort: 32400

ingress:
  main:
    enabled: true
    hosts:
      - host: plex.nooney.dev
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
  media:
    enabled: true
    type: hostPath
    hostPath: /mnt/media
  transcode:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 2Gi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi
