image:
  repository: ghcr.io/home-operations/plex
  tag: 1.43.0
  pullPolicy: IfNotPresent

env:
  TZ: "Europe/London"
  PLEX_CLAIM: ""
  ADVERTISE_IP: "http://192.168.100.21:32400/"
  ALLOWED_NETWORKS: "192.168.100.0/24,10.244.0.0/16"

service:
  main:
    type: NodePort
    ports:
      http:
        port: 32400
        nodePort: 32400

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
  media:
    enabled: true
    type: hostPath
    hostPath: /mnt/media
    mountPath: /mnt/media
  transcode:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 2Gi
    mountPath: /transcode

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi
